#!/usr/bin/env bash
set -o errexit

if ! hash mongo >/dev/null 2>&1; then
  printf "Can't find mongo, exiting!\n"
  exit 1
fi

MONGODB_VERSION=$(mongo --version | cut -d: -f2| awk '{ print $1 }')
USER=${MONGODB_USERNAME:-mongo}
PASS=${MONGODB_PASSWORD:-$(head -8 /dev/urandom  |sha1sum  |awk ' { print $1 }')}
DB=${MONGODB_DBNAME:-admin}
if [ ! -z "$MONGODB_DBNAME" ]
then
    ROLE=${MONGODB_ROLE:-dbOwner}
else
    ROLE=${MONGODB_ROLE:-dbAdminAnyDatabase}
fi

# Start MongoDB service
mkdir -p /data
/usr/bin/mongod --dbpath /data --nojournal &
while ! nc -vz localhost 27017; do sleep 4; done

# Create User
echo "Creating user: \"$USER\"..."
mongo $DB --eval "db.createUser({ user: '$USER', pwd: '$PASS', roles: [ { role: '$ROLE', db: '$DB' } ] });"

# Stop MongoDB service
/usr/bin/mongod --dbpath /data --shutdown

echo "========================================================================"
echo "MongoDB Version: \"$MONGODB_VERSION\""
echo "MongoDB User: \"$USER\""
echo "MongoDB Password: \"$PASS\""
echo "MongoDB Database: \"$DB\""
echo "MongoDB Role: \"$ROLE\""
echo "========================================================================"

/usr/bin/mongod --dbpath /data &
