#!/usr/bin/env bash
set -x
set -o errexit

if ! hash mongo >/dev/null 2>&1; then
  printf "Can't find mongo, exiting!\n"
  exit 1
fi

MONGODB_VERSION=$(mongo --version | cut -d: -f2| awk '{ print $1 }')
MUSER=${MONGODB_USERNAME:-mongo}
MPASS=${MONGODB_PASSWORD:-$(head -8 /dev/urandom  |sha1sum  |awk ' { print $1 }')}
MDB=${MONGODB_DBNAME:-admin}
if [ ! -z "$MONGODB_DBNAME" ]
then
    MROLE=${MONGODB_ROLE:-dbOwner}
else
    MROLE=${MONGODB_ROLE:-dbAdminAnyDatabase}
fi

# Start MongoDB service
mkdir -p /data
/usr/bin/mongod --dbpath /data --nojournal &
while ! nc -vz localhost 27017; do sleep 4; done

mongo24x ()
{
# Create User in mongo <=2.4
local USER=$1
local PASS=$2
local DB=$3
mongo admin --eval "db.addUser({ user: '$USER', pwd: '$PASS', roles: [ 'userAdminAnyDatabase'] });"
mongo $DB --eval "db.addUser({ user: '$USER', pwd: '$PASS', roles: [ 'userAdmin','readWrite','dbAdmin','$DB' ] });"
}

mongo26x ()
{
# Create User in mongo >=2.6
local USER=$1
local PASS=$2
local ROLE=$3
local DB=$4
mongo admin --eval "db.createUser({ user: '$USER', pwd: '$PASS', roles: [ { role: 'userAdminAnyDatabase', db: 'admin' } ] });"
mongo $DB --eval "db.createUser({ user: '$USER', pwd: '$PASS', roles: [ { role: '$ROLE', db: '$DB' } ] });"
}

if [[ ${MONGODB_VERSION} =~ ^3 ]]; then
  mongo26x $MUSER $MPASS $MROLE $MDB
  else
  mongo24x $MUSER $MPASS $MDB
fi

# Stop MongoDB service
/usr/bin/mongod --dbpath /data --shutdown
sleep 3
echo "========================================================================"
echo "MongoDB Version: \"$MONGODB_VERSION\""
echo "MongoDB User: \"$MUSER\""
echo "MongoDB Password: \"$MPASS\""
echo "MongoDB Database: \"$MDB\""
echo "MongoDB Role: \"$MROLE\""
echo "========================================================================"

mongod --dbpath /data --auth
